### ISSUE TITLE
Incorrect pixels on index page hero section

### ISSUE THREAD

**Issue by Izzatillo075** [byStrange/kia.uz-frontend#36]

**Comment by Izzatillo075** [comment]
![image](https://github.com/user-attachments/assets/894fb75a-fbd9-45a5-bdf1-eb4677c04452)
![image](https://github.com/user-attachments/assets/aab5d727-5fab-49e3-8787-0492f20dc15c)



Check the pixels and sizes fully of this page

**Comment by byStrange** [comment]
Where are the issues, can u be more specific please?
