### ISSUE TITLE
Wrong position

### ISSUE THREAD

**Issue by Izzatillo075** [byStrange/kia.uz-frontend#37]
![image](https://github.com/user-attachments/assets/f370f6b9-1bea-4c49-bfca-a93cf997b584)
![image](https://github.com/user-attachments/assets/c4150f7a-41ef-4f2c-a008-fb8848e51669)

1. button labeled as "Подробнее о модели" is thinner and longer on design
but shorter and bolder on website

![image](https://github.com/user-attachments/assets/05f61b12-c750-45a8-ac0b-dfea246ef928)
![image](https://github.com/user-attachments/assets/cd2f6973-3d40-4bb8-9db0-6da04beab498)
2. Wrong positions of car models on the top

**Comment by byStrange** [comment]
1. Button width depends on the screen, on the design screen is 375px for mobile devices (so consider your screen width). About the font weight, its same as on the design. There was actually error on buttons vertical padding. I fixed it with #42

2. It will be worked on another issue 
https://github.com/byStrange/kia.uz-frontend/issues/40
