### ISSUE TITLE
Color issue

### ISSUE THREAD

**Issue by Izzatillo075** [byStrange/kia.uz-frontend#55]
![image](https://github.com/user-attachments/assets/655c0cb3-8fef-49a6-83b9-ab278fd095a6)
Color of NEXT button is gray in design

![image](https://github.com/user-attachments/assets/4fe83944-4887-4313-be2f-937d06422a1d)
Color of NEXT button is black in website

**Comment by Izzatillo075** [comment]
Also their gap is different in website

**Comment by byStrange** [comment]
its because when you hover the button, button's background should be primary color. But if it's touch device like tablet, phone that can not "hover" elements like we can do on laptop button won't change and will not get "non-hover" state style. But instead will be same as "hover" state
